import colorama
import grid
import string as str

a = str.ascii_letters
b = """!"$%&'()+,-./:;<=>?@[\]^_`{|}~
"""
c = a + b
def printgrid(n):
    if n == "1":
        print("|" + colorama.Fore.BLACK+ colorama.Back.WHITE + '1' + colorama.Style.RESET_ALL + '|', end="")
        print(grid.two, end="")
        print(grid.three)
        print(grid.four, end="")
        print(grid.five, end="")
        print(grid.six)
        print(grid.seven, end="")
        print(grid.eight, end="")
        print(grid.nine)
        print(grid.asterisks, end="")
        print(grid.zero, end="")
        print(grid.hash)
    elif n == "2":
        print(grid.one, end="")
        print(colorama.Fore.BLACK+ colorama.Back.WHITE + '2' + colorama.Style.RESET_ALL + '|', end="")
        print(grid.three)
        print(grid.four, end="")
        print(grid.five, end="")
        print(grid.six)
        print(grid.seven, end="")
        print(grid.eight, end="")
        print(grid.nine)
        print(grid.asterisks, end="")
        print(grid.zero, end="")
        print(grid.hash)
    elif n == "3":
        print(grid.one, end="")
        print(grid.two, end ="")
        print(colorama.Fore.BLACK+ colorama.Back.WHITE + '3' + colorama.Style.RESET_ALL + '|')
        print(grid.four, end="")
        print(grid.five, end="")
        print(grid.six)
        print(grid.seven, end="")
        print(grid.eight, end="")
        print(grid.nine)
        print(grid.asterisks, end="")
        print(grid.zero, end="")
        print(grid.hash)
    elif n == "4":
        print(grid.one, end="")
        print(grid.two, end ="")
        print(grid.three)
        print("|" + colorama.Fore.BLACK+ colorama.Back.WHITE + '4' + colorama.Style.RESET_ALL + '|', end="")
        print(grid.five, end="")
        print(grid.six)
        print(grid.seven, end="")
        print(grid.eight, end="")
        print(grid.nine)
        print(grid.asterisks, end="")
        print(grid.zero, end="")
        print(grid.hash)
    elif n == "5":
        print(grid.one, end="")
        print(grid.two, end ="")
        print(grid.three)
        print(grid.four, end="")
        print(colorama.Fore.BLACK+ colorama.Back.WHITE + '5' + colorama.Style.RESET_ALL + '|', end="")
        print(grid.six)
        print(grid.seven, end="")
        print(grid.eight, end="")
        print(grid.nine)
        print(grid.asterisks, end="")
        print(grid.zero, end="")
        print(grid.hash)
    elif n == "6":
        print(grid.one, end="")
        print(grid.two, end ="")
        print(grid.three)
        print(grid.four, end="")
        print(grid.five, end="")
        print(colorama.Fore.BLACK+ colorama.Back.WHITE + '6' + colorama.Style.RESET_ALL + '|')
        print(grid.seven, end="")
        print(grid.eight, end="")
        print(grid.nine)
        print(grid.asterisks, end="")
        print(grid.zero, end="")
        print(grid.hash)
    elif n == "7":
        print(grid.one, end="")
        print(grid.two, end ="")
        print(grid.three)
        print(grid.four, end = "")
        print(grid.five, end="")
        print(grid.six)
        print("|" + colorama.Fore.BLACK+ colorama.Back.WHITE + '7' + colorama.Style.RESET_ALL + '|', end="")
        print(grid.eight, end="")
        print(grid.nine)
        print(grid.asterisks, end="")
        print(grid.zero, end="")
        print(grid.hash)
    elif n == "8":
        print(grid.one, end="")
        print(grid.two, end ="")
        print(grid.three)
        print(grid.four, end="")
        print(grid.five, end ="")
        print(grid.six)
        print(grid.seven, end="")
        print(colorama.Fore.BLACK+ colorama.Back.WHITE + '5' + colorama.Style.RESET_ALL + '|', end="")
        print(grid.nine)
        print(grid.asterisks, end="")
        print(grid.zero, end="")
        print(grid.hash)
    elif n == "9":
        print(grid.one, end="")
        print(grid.two, end ="")
        print(grid.three)
        print(grid.four, end="")
        print(grid.five, end ="")
        print(grid.six)
        print(grid.seven, end="")
        print(grid.eight, end="")
        print(colorama.Fore.BLACK+ colorama.Back.WHITE + '6' + colorama.Style.RESET_ALL + '|')
        print(grid.asterisks, end="")
        print(grid.zero, end="")
        print(grid.hash)
    elif n == "*":
        print(grid.one, end="")
        print(grid.two, end ="")
        print(grid.three)
        print(grid.four, end = "")
        print(grid.five, end="")
        print(grid.six)
        print(grid.seven, end = "")
        print(grid.eight, end="")
        print(grid.nine)
        print("|" + colorama.Fore.BLACK+ colorama.Back.WHITE + '*' + colorama.Style.RESET_ALL + '|', end="")
        print(grid.zero, end="")
        print(grid.hash)
    elif n == '0':
        print(grid.one, end="")
        print(grid.two, end ="")
        print(grid.three)
        print(grid.four, end="")
        print(grid.five, end ="")
        print(grid.six)
        print(grid.seven, end="")
        print(grid.eight, end = "")
        print(grid.nine)
        print(grid.asterisks, end="")
        print(colorama.Fore.BLACK+ colorama.Back.WHITE + '0' + colorama.Style.RESET_ALL + '|', end="")
        print(grid.hash)
    elif n == "#":
        print(grid.one, end="")
        print(grid.two, end ="")
        print(grid.three)
        print(grid.four, end="")
        print(grid.five, end ="")
        print(grid.six)
        print(grid.seven, end="")
        print(grid.eight, end = "")
        print(grid.nine)
        print(grid.asterisks, end="")
        print(grid.zero, end = "")
        print(colorama.Fore.BLACK+ colorama.Back.WHITE + '#' + colorama.Style.RESET_ALL + '|')

    
while True:
    a = input("Please enter password only with 0 to 9 and '*' and '#' ('e' to exit): ")
    if a == "e":
        break
    j = 0
    b = list(a)
    for i in b:
        if i in c:
            print("Please follow the given guidelines")
            j = 1
            break
    if j == 1:
        continue
    for i in b:
        printgrid(i)
        input("Please press enter for the next line to come: ")
        print()
        